Traceback (most recent call last):
  File "C:\Users\16478\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "C:\Users\16478\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\16478\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\16478\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\16478\Anaconda3\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Users\16478\Anaconda3\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\16478\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\16478\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# import packages
import numpy as np
import matplotlib.pyplot as plt
import os

for filename in os.listdir('data/em_vs_laser/'): #os.listdir() will return each file in a folder.
    wavelength, intensity = np.genfromtxt(f'data/em_vs_laser/{filename}',skip_header=14,delimiter='',unpack=True) # import the data from that file
    # check if filename has the word Integration in it
    if 'Integration' in filename:
        label = filename.split(' ')[8] # Extract the integration time from the filename using the tools discussed above
        plt.plot(wavelength,intensity,label=label) # plot the intensity
    # we don't define an else statement, so if the filename does not have the word Integration in it, nothing will happen.

# add labels and legend
plt.xlabel('wavelength')
plt.ylabel('intensity (a.u.)')
plt.legend()
legend.set_title('Integration time (ms)')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-7-3cc91fc37843>[0m in [0;36m<module>[1;34m[0m
[0;32m     16[0m [0mplt[0m[1;33m.[0m[0mylabel[0m[1;33m([0m[1;34m'intensity (a.u.)'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     17[0m [0mplt[0m[1;33m.[0m[0mlegend[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 18[1;33m [0mlegend[0m[1;33m.[0m[0mset_title[0m[1;33m([0m[1;34m'Integration time (ms)'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mNameError[0m: name 'legend' is not defined
NameError: name 'legend' is not defined

